---
# Based on https://docs.docker.com/engine/install/debian/
- name: Make sure older versions are not installed
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install dependancies for APT repo
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG key for APT
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
    update_cache: true

- name: Install Docker Engine
  apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add the user mathieu to the docker group
  ansible.builtin.user:
    name: mathieu
    groups: docker
    append: yes

- name: Add the user ansible to the docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: yes
