---
- name: "Install Gitlab python3 package"
  pip:
    name: python-gitlab
    state: present

- name: "Create GitLab Users"
  community.general.gitlab_user:
    api_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    validate_certs: True
    confirm: no
    api_token: "{{ gitlab_api_token_etna }}"
    name: "{{ item.name }}"
    username: "{{ item.name }}"
    password: "{{ gitlab_teacher_password }}"
    email: "{{ item.name }}@etna-alternance.net"
    state: blocked
    access_level: owner
  loop:
    - { name: 'rinaz_a' }
    - { name: 'maudui_t' }
    - { name: 'rafina_d' }
    - { name: 'beauco_j' }
  tags: users
