---
- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Install GitLab dependencies.
  package:
    name:
      - postfix
      - curl
      - openssl
      - tzdata
    state: present

- name: Install GitLab dependencies (Debian) and pip.
  apt:
    name:
      - gnupg2
      - python3-pip
    state: present

- name: Download GitLab repository installation script.
  get_url:
    url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh"
    dest: /tmp/gitlab_install_repository.sh
    validate_certs: true
  when: not gitlab_file.stat.exists

- name: Install GitLab repository.
  command: bash /tmp/gitlab_install_repository.sh
  register: output
  when: not gitlab_file.stat.exists

- name: Install GitLab
  apt:
    update_cache: true
    name:
      - gitlab-ce
  environment:
    EXTERNAL_URL: "http://gitlab.mybooking.services"
    GITLAB_ROOT_PASSWORD: " {{ gitlab_root_password }} "

- name: Restart Gitlab
  command: gitlab-ctl restart
  when: not gitlab_file.stat.exists

- name: Show default root password
  debug:
    msg: "root password is : {{ gitlab_root_password }}"
  when: not gitlab_file.stat.exists

- name: Pause for 1 minute to wait for Gitlab server to cool down
  pause:
    minutes: 1
  when: not gitlab_file.stat.exists
