---
- name: Install python3-docker
  apt:
    name: python3-docker
    state: present

- name: Pull docker images from Docker Hub
  docker_image:
    name: "{{ item.name }}"
    tag: latest
    source: pull
  when: "inventory_hostname == groups['workers'][0]"
  loop:
    - { name: 'telegraf' }
    - { name: 'influxdb' }
    - { name: 'chronograf' }
    - { name: 'kapacitor' }

- name: Push docker images to registry.mybooking.services
  docker_image:
    name: "{{ item.name }}"
    repository: "registry.mybooking.services:5000/{{ item.name }}:v1"
    tag: latest
    push: yes
    source: local
  loop:
    - { name: 'telegraf' }
    - { name: 'influxdb' }
    - { name: 'chronograf' }
    - { name: 'kapacitor' }
  when: "inventory_hostname == groups['workers'][0]"
