---
- name: Create swarm service for TICK
  docker_swarm_service:
    name: "{{ item.name }}"
    image: "{{ item.name }}"
    state: present
  #   mounts:
  #     - source: /opt/registry/data
  #       target: /var/lib/registry
  #       type: bind
  #     - source: /opt/registry/certs
  #       target: /certs
  #       type: bind
  #   publish:
  #     - published_port: 5000
  #       target_port: 5000
  #   env:
  #     REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.mybooking.services.crt
  #     REGISTRY_HTTP_TLS_KEY: /certs/registry.mybooking.services.pem
  #     REGISTRY_HTTP_ADDR: 0.0.0.0:5000
  #     REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
  loop:
    - { name: 'telegraf' }
    - { name: 'influxdb' }
    - { name: 'chronograf' }
    - { name: 'kapacitor' }
  # when: "'managers' in group_names"
