---
- name: Install python3-docker
  apt:
    name: python3-docker
    state: present

- name: Install telegraf
  docker_swarm_service:
    name: telegraf
    image: "registry.mybooking.services:5000/telegraf:v1"
    state: present
    mounts:
      - source: /tmp/
        target: /my_tmp/
        type: bind
    configs:
      - config_name: telegraf-conf
        filename: "/etc/telegraf/telegraf.conf"
    publish:
      - published_port: 8186
        target_port: 8186
  when: "inventory_hostname == groups['workers'][0]"
