---
- name: Install python3-docker
  apt:
    name: python3-docker
    state: present

- name: Copy telegraf.conf to /tmp on {{ inventory_hostname }}
  copy:
    src: data/telegraf.conf
    dest: /tmp/telegraf.conf

- name: Install telegraf
  docker_swarm_service:
    name: telegraf
    image: "registry.mybooking.services:5000/telegraf:v1"
    state: present
    configs:
      - config_name: telegraf.conf
        filename: "/tmp/telegraf.conf"

    publish:
      - published_port: 8186
        target_port: 8186
