---
- name: Pull docker images from Docker Hub
  docker_image:
    name: traefik
    tag: v2.4
    source: pull

- name: Push docker images to registry.mybooking.services
  docker_image:
    name: "traefik:v2.4"
    repository: "registry.mybooking.services:5000/traefik:v1"
    push: yes
    source: local

- name: Remove Docker Hub images from host
  docker_image:
    state: absent
    name: "traefik:v2.4"
