version: '3.9'

services:

  reverse-proxy:
    image: traefik:v2.4
    container_name: traefik
    ports:
      - 80:80
      - 8080:8080
    # deploy:
    #   labels:
    #     - traefik.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

  manage:
    image: nginx
    #container_name: manage
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 3s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.manage.rule=Host(`manage.mybooking.services`)"
        - "traefik.http.routers.manage.entrypoints=mybooking"
        - "traefik.http.services.manage-service.loadbalancer.server.port=8081"

  book:
    image: nginx
    container_name: book
    # deploy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.book.rule=Host(`book.mybooking.services`)"
      - "traefik.http.routers.book.entrypoints=mybooking"

  users:
    image: nginx
    container_name: users
    # deploy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=Host(`users.mybooking.services`)"
      - "traefik.http.routers.users.entrypoints=mybooking"
