[accessLog]

[log]
  level = "INFO"

[api]
  insecure = true
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.mybooking]
    address = ":80"

[providers]
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    swarmMode = true