---
- name: Install pyOpenSSL dependancies
  apt:
    name:
      - python3-pip
      - gcc
      - rustc
      - libssl-dev
    update_cache: yes

- name: Install python-pyOpenSSL
  pip:
    name:
      - pyOpenSSL
    state: present
  when: "'managers' in group_names"

- name : Create private key
  openssl_privatekey:
    path: /etc/ssl/private/registry.mybooking.services.pem
  when: "'managers' in group_names"

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: /etc/ssl/csr/registry.mybooking.services.csr
    privatekey_path: /etc/ssl/private/registry.mybooking.services.pem
    common_name: registry.my
  when: "'managers' in group_names"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/crt/registry.mybooking.services.crt
    privatekey_path: /etc/ssl/private/registry.mybooking.services.pem
    csr_path: /etc/ssl/csr/registry.mybooking.services.csr
    provider: selfsigned
  when: "'managers' in group_names"

- name: Grab generated cert to localhost
  fetch:
    src: /etc/ssl/crt/registry.mybooking.services.crt
    dest: /tmp/registry.mybooking.services.crt
    flat: true
  when: "'managers' in group_names"

- name: Export cert to other nodes
  copy:
    src: /tmp/registry.mybooking.services.crt
    dest: /etc/ssl/private/
