---
- name: Register runner
  ansible.builtin.command: |
    gitlab-runner  register \
    --non-interactive \
    --url "http://{{ gitlab_hostname }}" \
    --registration-token "{{ registration_token }}" \
    --executor "docker" \
    --docker-image alpine:latest \
    --description "docker-runner" \
    --tag-list "docker,aws" \
    --run-untagged="true" \
    --locked="false" \
    --access-level="not_protected" \
    --docker-network-mode my_net \
    --clone-url="http://{{ gitlab_ip }}"
