---
- name: "Install python-gitlab"
  pip:
    name: python-gitlab
    state: present
  when: "'manager' in inventory_hostname"

- name: "Copy config.toml file"
  copy:
    src: data/gitlab_runner/config.toml
    dest: /etc/gitlab-runner/config.toml
    mode: '0644'

- name: "Register a runner"
  community.general.gitlab_runner:
    #api_url: "http://192.168.47.134" #Works
    api_url: "http://{{ hostvars['worker1']['ansible_default_ipv4']['address'] }}" #DO not work
    api_token: "{{ gitlab_api_token_alex }}"
    registration_token: "{{ gitlab_runner_registration_token }}"
    description: Docker machine test ansible register runner
    state: present
    active: true
    tag_list: ['docker']
    run_untagged: false
