[tool.poetry]
name = "booking-manager"
version = "0.1.0"
description = "Booking manager API"
authors = ["hauteb_m"]

[tool.poetry.dependencies]
python = "^3.7"
uvicorn = "^0.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
