---
- hosts: "all"
  vars_files:
    - vars/gitlab.yml
  roles:
    - role: gitlab_install
      tags:
      - install
      - users
      when: "'worker1' in inventory_hostname"

    - role: gitlab_runner
      tags:
      - install_runner
      when: "'worker1' in inventory_hostname"
