---
- hosts: "all"
  roles:
    - { role: setup,            tags: ['setup'] }
    - { role: docker_swarm,     tags: ['docker_swarm'] }
    - { role: docker_registry,  tags: ['docker_registry'] }
    - { role: gitlab,           tags: ['gitlab'] }
