[http]
  [http.routers]
    [http.routers.test-service]
      rule = "Host(`test.com`) && PathPrefix(`/whoami/`)"
      service = "whoami"
      entryPoints = ["manage"]

  [http.services]
    [http.services.manage]
      [http.services.manage.loadBalancer]
        [[http.services.manage.loadBalancer.servers]]
          url = "http://127.0.0.1:8081"