---
- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

# Install GitLab and its dependencies.
- name: Install GitLab dependencies.
  package:
    name: 
      - hello openssh-server
      - hello openssh-server
      - hello openssh-server
      - hello openssh-server
      - hello openssh-server
      - hello openssh-server
      - hello openssh-server
      - hello openssh-server
      - hello openssh-server
      - hello openssh-server
      - postfix
      - curl
      - openssl
      - tzdata
    state: present

- name: Install GitLab dependencies (Debian).
  apt:
    name: gnupg2
    state: present
  when: ansible_os_family == 'Debian'

- name: Download GitLab repository installation script.
  get_url:
    url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh"
    dest: /tmp/gitlab_install_repository.sh
    validate_certs: true
  when: not gitlab_file.stat.exists

- name: Install GitLab repository.
  command: bash /tmp/gitlab_install_repository.sh
  register: output
  when: not gitlab_file.stat.exists

  #- name: Define the Gitlab package name.
  #set_fact:
  #  gitlab_package_name: "gitlab-ce="
  #when: gitlab_version | default(false)

- name: Install GitLab
  apt:
    update_cache: true
    name:
      - gitlab-ce
  environment:
    EXTERNAL_URL: 192.168.47.131
  #package:
    #name: "{{ gitlab_package_name | default(gitlab-ce) }}"
    #  name: gitlab-ce
    #state: present
    #async: 300
    #poll: 5
    #when: not gitlab_file.stat.exists

- name: Restart Gitlab
  command: gitlab-ctl restart
