name: Booking API

on:
  push:
    paths:
      - 'APIs/booking/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.8, 3.9]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: mybookingservices
          MYSQL_USER:
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip and tools
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install poetry virtualenv flake8 mypy pytest pytest-cov

    - name: Install booking API
      working-directory : ./APIs/booking
      run: |
        virtualenv -p python3 env
        . env/bin/activate
        poetry install

    - name: Run linter tests
      working-directory : ./APIs/booking
      run: |
        flake8

    - name: Run unit tests
      working-directory : ./APIs/booking
      run: |
        . env/bin/activate
        python3 -m pip install requests
        pytest -sv  --cov-report term-missing --cov=booking

    - name: Build the booking API
      working-directory : ./APIs/booking
      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
      run: |
        . env/bin/activate
        poetry build
