name: docs

on:
  # Trigger the docs build only on main
  push:
    branches:
      - main
      - develop
      - matteyeux/docs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8


    - name: Install graphviz
      run: |
        sudo apt install graphviz

    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install poetry virtualenv

    - name: Create shared virtualenv
      working-directory : ./APIs
      run: |
        virtualenv -p python3 env

    - name: Install booking API
      working-directory : APIs/booking
      run: |
        . ../env/bin/activate
        poetry install

    - name: Build documentation
      working-directory : ./docs
      run: |
        . ../APIs/env/bin/activate
        pip3 install -r requirements.txt
        make html
        rm -rf build/doctrees

    - name: Archive docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: |
          docs/build
